// Code generated by packages/protocol/scripts/display-vocabulary.ts; DO NOT EDIT.

package live.cohub.android.display

internal object DisplayVocabulary {
    const val MAX_DISPLAYS = 16
    const val MAX_NAME_LEN = 200
    const val MAX_DIMENSION = 16384
    const val MAX_INPUT_EVENTS = 512
    const val MAX_INPUT_TEXT_LEN = 4096
    const val MAX_KEY_LEN = 64
    const val MAX_INPUT_SCHEDULE_MS = 60000
    const val MAX_SCROLL = 10
    const val DEFAULT_MAX_SIZE = 1920
    const val DEFAULT_TREE_ELEMENTS = 300
    const val MAX_TREE_ELEMENTS = 1000
    const val MAX_TREE_DEPTH = 64
    const val MAX_ELEMENT_TEXT = 500
    val SYSTEM_ACTIONS = setOf("back", "home", "recents", "notifications", "quickSettings", "lock")
    val PERMISSIONS = setOf("screenRecording", "accessibility")
    val POINTER_ACTIONS = setOf("down", "move", "up", "cancel")
    val KEY_ACTIONS = setOf("down", "up", "press")
    val BUTTONS = setOf("primary", "secondary", "middle")
    val ELEMENT_ROLES = setOf("window", "dialog", "group", "list", "listItem", "text", "heading", "image", "button", "link", "textField", "checkbox", "radio", "switch", "slider", "tab", "menu", "menuItem", "web", "other")
    val ELEMENT_STATES = setOf("focused", "selected", "checked", "disabled", "editable", "password", "scrollable", "expanded")
    val ELEMENT_ACTIONS = setOf("click", "longPress", "focus", "setText", "scrollForward", "scrollBackward")
}
