// Cloudflare Worker entry for the web app.
//
// Standalone App origins get one App per hostname, so every path on such a host
// belongs to that App. Those requests must be resolved here, before the
// SvelteKit adapter runs: the adapter serves prerendered paths (`/`, `/docs`,
// `/pricing`, …) straight from static assets, which would otherwise answer with
// the marketing shell instead of the App.
//
// Wrangler bundles this entry together with the adapter's `_worker.js` and its
// build-output imports, so `main` points here instead of at the adapter file.
// This is the only place standalone origins are resolved. `vite dev` serves the
// SvelteKit dev server and `pnpm preview` runs `wrangler dev`, both without this
// entry, so standalone origins are not served there.
//
// `run_worker_first` routes every request through the Worker, and the adapter
// only serves the static assets in its own manifest. Build-generated files such
// as the PWA service worker are served here from `ASSETS` instead — after the
// standalone check, so an App's own `/sw.js` is never shadowed.
//
// `#worker-entry-deps` is generated by `scripts/generate-worker-entry-deps.mjs`
// after `vite build`; `src/entry.worker-deps.d.ts` types it and references this
// file, which sits outside the generated tsconfig `include`. The request logic
// lives in `src/lib/server/standalone-host-request.ts`.

import {
	adapter,
	GENERATED_ASSET_PATHS,
	PUBLIC_API_ORIGIN,
	PUBLIC_APP_STANDALONE_HOST_TEMPLATE,
} from "#worker-entry-deps";
import { serveStandaloneHostRequest } from "./src/lib/server/standalone-host-request.ts";

const generatedAssetPaths = new Set(GENERATED_ASSET_PATHS);

const entry: typeof adapter = {
	fetch(request, env, ctx) {
		const url = new URL(request.url);
		// Cloudflare requires `fetch` bound to its global receiver; handler
		// entrypoints are called as plain functions, so `this` is not usable.
		const standalone = serveStandaloneHostRequest({
			request,
			url,
			template: PUBLIC_APP_STANDALONE_HOST_TEMPLATE,
			apiOrigin: PUBLIC_API_ORIGIN,
			fetcher: fetch.bind(globalThis),
			waitUntil: (promise) => ctx.waitUntil(promise),
		});
		if (standalone) return standalone;
		if (generatedAssetPaths.has(url.pathname)) return env.ASSETS.fetch(request);
		return adapter.fetch(request, env, ctx);
	},
};

export default entry;
