/**
 * Generates the display vocabulary and limits for sandboxd (Go) and the
 * Android provider (Kotlin) from `src/display`, their one source.
 *
 *   pnpm --filter @cohub/protocol generate:display
 *
 * `display.test.ts` fails when a generated file is out of date.
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import * as display from "../src/display/index.js";

const HEADER = "Code generated by packages/protocol/scripts/display-vocabulary.ts; DO NOT EDIT.";

export const GENERATED = {
  go: fileURLToPath(new URL("../../../apps/sandbox/display/vocabulary_gen.go", import.meta.url)),
  kotlin: fileURLToPath(
    new URL("../../../apps/android/app/src/main/kotlin/live/cohub/android/display/DisplayVocabulary.kt", import.meta.url),
  ),
};

const lists = {
  systemActions: display.DISPLAY_SYSTEM_ACTIONS,
  permissions: display.DISPLAY_PERMISSIONS,
  pointerActions: display.DISPLAY_POINTER_ACTIONS,
  keyActions: display.DISPLAY_KEY_ACTIONS,
  buttons: display.DISPLAY_BUTTONS,
  elementRoles: display.DISPLAY_ELEMENT_ROLES,
  elementStates: display.DISPLAY_ELEMENT_STATES,
  elementActions: display.DISPLAY_ELEMENT_ACTIONS,
};

const limits = {
  maxDisplays: display.DISPLAYS_MAX,
  maxNameLen: display.DISPLAY_NAME_MAX,
  maxDimension: display.DISPLAY_DIMENSION_MAX,
  maxInputEvents: display.DISPLAY_INPUT_MAX_EVENTS,
  maxInputTextLen: display.DISPLAY_INPUT_MAX_TEXT,
  maxKeyLen: display.DISPLAY_INPUT_MAX_KEY,
  maxInputScheduleMs: display.DISPLAY_INPUT_MAX_SCHEDULE_MS,
  maxScroll: display.DISPLAY_SCROLL_MAX,
  defaultMaxSize: display.DISPLAY_CAPTURE_DEFAULT_MAX_SIZE,
  defaultTreeElements: display.DISPLAY_TREE_DEFAULT_ELEMENTS,
  maxTreeElements: display.DISPLAY_TREE_MAX_ELEMENTS,
  maxTreeDepth: display.DISPLAY_TREE_MAX_DEPTH,
  maxElementText: display.DISPLAY_ELEMENT_TEXT_MAX,
};

const patterns = {
  displayIDPattern: display.DISPLAY_ID_PATTERN,
  elementRefPattern: display.DISPLAY_ELEMENT_REF_PATTERN,
};

const upper = (name: string) => name.charAt(0).toUpperCase() + name.slice(1);
const constant = (name: string) => name.replace(/[A-Z]/g, (letter) => `_${letter}`).toUpperCase();
const quote = (value: string) => JSON.stringify(value);

export function renderGo(): string {
  const width = Math.max(...Object.keys(limits).map((name) => upper(name).length));
  const names = Math.max(...[...Object.keys(patterns), ...Object.keys(lists)].map((name) => name.length));
  return [
    `// ${HEADER}`,
    "",
    "package display",
    "",
    'import "regexp"',
    "",
    "const (",
    ...Object.entries(limits).map(([name, value]) => `\t${upper(name).padEnd(width)} = ${value}`),
    ")",
    "",
    "var (",
    ...Object.entries(patterns).map(([name, pattern]) => `\t${name.padEnd(names)} = regexp.MustCompile(\`${pattern.source}\`)`),
    ...Object.entries(lists).map(([name, values]) => `\t${name.padEnd(names)} = names(${values.map(quote).join(", ")})`),
    ")",
    "",
  ].join("\n");
}

export function renderKotlin(): string {
  return [
    `// ${HEADER}`,
    "",
    "package live.cohub.android.display",
    "",
    "internal object DisplayVocabulary {",
    ...Object.entries(limits).map(([name, value]) => `    const val ${constant(name)} = ${value}`),
    ...Object.entries(lists).map(([name, values]) => `    val ${constant(name)} = setOf(${values.map(quote).join(", ")})`),
    "}",
    "",
  ].join("\n");
}

export async function stale(): Promise<string[]> {
  const out: string[] = [];
  for (const [path, render] of [[GENERATED.go, renderGo], [GENERATED.kotlin, renderKotlin]] as const) {
    const current = await readFile(path, "utf8").catch(() => "");
    if (current !== render()) out.push(path);
  }
  return out;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await writeFile(GENERATED.go, renderGo());
  await writeFile(GENERATED.kotlin, renderKotlin());
}
