// Types for the build outputs `entry.worker.ts` imports.
//
// `_worker.js` and `worker-entry-env.js` are generated by `vite build` (the
// SvelteKit adapter and `scripts/generate-worker-entry-env.mjs`) under
// `.svelte-kit`, which is gitignored and absent on a fresh checkout.
//
// `scripts/generate-worker-entry-env.mjs` also writes a sibling `.d.ts` for each
// generated module, so TypeScript resolves the declaration instead of walking
// into the generated JavaScript. These declarations cover the fresh-checkout
// case, where the siblings do not exist yet.

declare module "*/_worker.js" {
	/** Shape of the Worker the SvelteKit adapter generates. */
	const worker: {
		fetch(request: Request, env: unknown, ctx: unknown): Promise<Response>;
	};
	export default worker;
}

declare module "*/worker-entry-env.js" {
	/** Origin of the API this deployment talks to. */
	export const PUBLIC_API_ORIGIN: string;
	/** Hostname template for standalone App origins; empty disables them. */
	export const PUBLIC_APP_STANDALONE_HOST_TEMPLATE: string;
}
