/// <reference path="../entry.worker.ts" />

/**
 * Types for `#worker-entry-deps`, the build outputs `entry.worker.ts` imports.
 *
 * The implementation is generated by `vite build` (the SvelteKit adapter and
 * `scripts/generate-worker-entry-deps.mjs`) under `.svelte-kit`, which is
 * gitignored and therefore absent on a fresh checkout. Declaring it here keeps a
 * fresh checkout typechecking, without pulling the generated JavaScript into
 * `checkJs`.
 *
 * `package.json` maps this declaration and the generated module to the
 * `#worker-entry-deps` specifier. The reference above pulls the entry itself into
 * the program: it lives at the package root, which the generated `include` does
 * not cover, and `include` cannot be extended without replacing that list.
 */

/** The part of the Workers `ExecutionContext` the entry relies on. */
export interface WorkerExecutionContext {
	waitUntil(promise: Promise<unknown>): void;
}

/** The part of the Worker bindings the entry relies on. */
export interface WorkerEnv {
	ASSETS: { fetch(request: Request): Promise<Response> };
}

/** The Worker the SvelteKit adapter generates. */
export declare const adapter: {
	fetch(
		request: Request,
		env: WorkerEnv,
		ctx: WorkerExecutionContext,
	): Promise<Response>;
};

/** Origin of the API this deployment talks to. */
export declare const PUBLIC_API_ORIGIN: string;

/** Hostname template for standalone App origins; empty disables them. */
export declare const PUBLIC_APP_STANDALONE_HOST_TEMPLATE: string;

/**
 * Client build files outside the adapter's asset manifest (vite-plugin-pwa's
 * `sw.js`, `workbox-*.js`, `manifest.webmanifest`), as URL paths.
 */
export declare const GENERATED_ASSET_PATHS: readonly string[];
