/**
 * Types for `#worker-entry-deps`, the build outputs `entry.worker.ts` imports.
 *
 * The implementation is generated by `vite build` (the SvelteKit adapter and
 * `scripts/generate-worker-entry-env.mjs`) under `.svelte-kit`, which is
 * gitignored and therefore absent on a fresh checkout. Declaring it here keeps
 * the entry inside the TypeScript program in every checkout, without pulling the
 * generated JavaScript into `checkJs`.
 *
 * `package.json` maps this declaration and the generated module to the
 * `#worker-entry-deps` specifier.
 */

/** The Worker the SvelteKit adapter generates. */
export declare const adapter: {
	fetch(request: Request, env: unknown, ctx: unknown): Promise<Response>;
};

/** Origin of the API this deployment talks to. */
export declare const PUBLIC_API_ORIGIN: string;

/** Hostname template for standalone App origins; empty disables them. */
export declare const PUBLIC_APP_STANDALONE_HOST_TEMPLATE: string;
