// Code generated by packages/protocol/scripts/display-vocabulary.ts; DO NOT EDIT.

package display

import "regexp"

const (
	MaxDisplays         = 16
	MaxNameLen          = 200
	MaxDimension        = 16384
	MaxInputEvents      = 512
	MaxInputTextLen     = 4096
	MaxKeyLen           = 64
	MaxInputScheduleMs  = 60000
	MaxScroll           = 10
	DefaultMaxSize      = 1920
	DefaultTreeElements = 300
	MaxTreeElements     = 1000
	MaxTreeDepth        = 64
	MaxElementText      = 500
)

var (
	displayIDPattern  = regexp.MustCompile(`^[A-Za-z0-9._-]{1,64}$`)
	elementRefPattern = regexp.MustCompile(`^e\d{1,9}\.\d{1,5}$`)
	systemActions     = names("back", "home", "recents", "notifications", "quickSettings", "lock")
	permissions       = names("screenRecording", "accessibility")
	pointerActions    = names("down", "move", "up", "cancel")
	keyActions        = names("down", "up", "press")
	buttons           = names("primary", "secondary", "middle")
	elementRoles      = names("window", "dialog", "group", "list", "listItem", "text", "heading", "image", "button", "link", "textField", "checkbox", "radio", "switch", "slider", "tab", "menu", "menuItem", "web", "other")
	elementStates     = names("focused", "selected", "checked", "disabled", "editable", "password", "scrollable", "expanded")
	elementActions    = names("click", "longPress", "focus", "setText", "scrollForward", "scrollBackward")
)
